export const FILMS = {
  // --- EMOTIONAL / DRAMA ---
  paradiso: {
    title: 'Cinema Paradiso', year: 1988, runtime: '2h 5m', rating: 'PG',
    dir: 'Giuseppe Tornatore',
    poster: { bg: 'linear-gradient(160deg,#6b2d2f,#2a0f12)', ink: '#F7C66B', kicker: 'NUOVO CINEMA' },
    imdb: 8.5, letterboxd: 4.4, where: ['Max', 'Criterion'],
    tags: ['Italy', 'Coming-of-age', 'Nostalgia'],
    blurb: 'A filmmaker remembers the Sicilian village where he fell in love with cinema — and the gruff projectionist who let him watch from the booth.',
  },
  pastlives: {
    title: 'Past Lives', year: 2023, runtime: '1h 45m', rating: 'PG-13',
    dir: 'Celine Song',
    poster: { bg: 'linear-gradient(160deg,#2f4a6b,#13202f)', ink: '#E9D7B0', kicker: 'PAST LIVES' },
    imdb: 7.8, letterboxd: 4.3, where: ['Paramount+', 'Prime'],
    tags: ['Quietly devastating', 'Modern', 'Romance'],
    blurb: 'Two childhood friends from Seoul reconnect across decades and continents, circling the question of who they might have been to each other.',
  },
  aftersun: {
    title: 'Aftersun', year: 2022, runtime: '1h 36m', rating: 'R',
    dir: 'Charlotte Wells',
    poster: { bg: 'linear-gradient(160deg,#1a3a5c,#0a1a2e)', ink: '#98D4E8', kicker: 'AFTERSUN' },
    imdb: 7.6, letterboxd: 4.3, where: ['MUBI', 'Prime'],
    tags: ['Memory', 'Father-daughter', 'Devastating'],
    blurb: 'A young woman revisits footage from a holiday she took with her father as a child, slowly realising what she missed at the time.',
  },
  thefarewell: {
    title: 'The Farewell', year: 2019, runtime: '1h 38m', rating: 'PG',
    dir: 'Lulu Wang',
    poster: { bg: 'linear-gradient(160deg,#2d4a1e,#0f1f0a)', ink: '#E8D5A0', kicker: 'THE FAREWELL' },
    imdb: 7.5, letterboxd: 4.1, where: ['Prime', 'Apple TV'],
    tags: ['Chinese-American', 'Family', 'Bittersweet'],
    blurb: 'A Chinese-American woman returns to China under the pretence of a wedding when her family decides not to tell her grandmother she has terminal cancer.',
  },
  coco: {
    title: 'Coco', year: 2017, runtime: '1h 45m', rating: 'PG',
    dir: 'Lee Unkrich',
    poster: { bg: 'linear-gradient(160deg,#7a1f6b,#2b0c24)', ink: '#FFD700', kicker: 'COCO' },
    imdb: 8.4, letterboxd: 4.3, where: ['Disney+'],
    tags: ['Family', 'Mexico', 'Music'],
    blurb: 'A young boy dreams of being a musician and accidentally lands in the Land of the Dead, where he must find his great-great-grandfather before sunrise.',
  },

  // --- FEEL-GOOD / UPLIFTING ---
  paddington: {
    title: 'Paddington 2', year: 2017, runtime: '1h 43m', rating: 'PG',
    dir: 'Paul King',
    poster: { bg: 'linear-gradient(160deg,#1f6f8b,#0e3340)', ink: '#F2B23C', kicker: 'PADDINGTON 2' },
    imdb: 8.2, letterboxd: 4.4, where: ['Max', 'Prime'],
    tags: ['Pure-hearted', 'Funny', 'Secretly perfect'],
    blurb: 'A polite young bear takes odd jobs to buy his aunt the perfect birthday gift — until the present is stolen and he must clear his name.',
  },
  brendanfraser: {
    title: 'The Whale', year: 2022, runtime: '1h 57m', rating: 'R',
    dir: 'Darren Aronofsky',
    poster: { bg: 'linear-gradient(160deg,#2a2a3a,#0f0f1a)', ink: '#C8B89A', kicker: 'THE WHALE' },
    imdb: 7.3, letterboxd: 3.8, where: ['Paramount+'],
    tags: ['Redemption', 'Family', 'Performance'],
    blurb: 'A reclusive English teacher attempts to reconnect with his estranged teenage daughter in one last chance at redemption.',
  },
  wonderfullife: {
    title: "It's a Wonderful Life", year: 1946, runtime: '2h 10m', rating: 'PG',
    dir: 'Frank Capra',
    poster: { bg: 'linear-gradient(160deg,#1a2a4a,#0a0f1e)', ink: '#E8D5B0', kicker: "IT'S A WONDERFUL LIFE" },
    imdb: 8.6, letterboxd: 4.4, where: ['Prime', 'Free on YouTube'],
    tags: ['Classic', 'Hopeful', 'Christmas'],
    blurb: 'A guardian angel shows a suicidal man what the world would have looked like had he never been born.',
  },
  hunt: {
    title: 'The Intouchables', year: 2011, runtime: '1h 52m', rating: 'R',
    dir: 'Olivier Nakache, Éric Toledano',
    poster: { bg: 'linear-gradient(160deg,#1a3a2a,#0a1f14)', ink: '#E8C87A', kicker: 'THE INTOUCHABLES' },
    imdb: 8.5, letterboxd: 4.3, where: ['Netflix', 'Prime'],
    tags: ['French', 'Friendship', 'Feel-good'],
    blurb: 'A wealthy quadriplegic hires an ex-convict as his caretaker — an unlikely friendship that changes both their lives.',
  },

  // --- THRILLER / INTENSE ---
  whiplash: {
    title: 'Whiplash', year: 2014, runtime: '1h 46m', rating: 'R',
    dir: 'Damien Chazelle',
    poster: { bg: 'linear-gradient(160deg,#3a3a3a,#0c0c0c)', ink: '#E4B33B', kicker: 'WHIPLASH' },
    imdb: 8.5, letterboxd: 4.3, where: ['Prime', 'Apple TV'],
    tags: ['Intense', 'Music', 'White-knuckle'],
    blurb: 'A driven young drummer at an elite conservatory pushes himself to the brink under a teacher whose methods blur mentorship and cruelty.',
  },
  parasite: {
    title: 'Parasite', year: 2019, runtime: '2h 12m', rating: 'R',
    dir: 'Bong Joon-ho',
    poster: { bg: 'linear-gradient(160deg,#1a1a2e,#16213e)', ink: '#E4B33B', kicker: '기생충' },
    imdb: 8.5, letterboxd: 4.5, where: ['Max', 'Hulu'],
    tags: ['Korean', 'Class', 'Genre-shifting'],
    blurb: 'A cash-strapped family schemes their way into the lives of a wealthy household — until an unexpected discovery upends everything.',
  },
  nocountry: {
    title: 'No Country for Old Men', year: 2007, runtime: '2h 2m', rating: 'R',
    dir: 'Coen Brothers',
    poster: { bg: 'linear-gradient(160deg,#3a2a1a,#1a0f0a)', ink: '#C8A870', kicker: 'NO COUNTRY' },
    imdb: 8.2, letterboxd: 4.3, where: ['Netflix', 'Prime'],
    tags: ['Neo-western', 'Relentless', 'Coen Brothers'],
    blurb: 'A hunter stumbles upon a drug deal gone wrong and a briefcase full of cash — and the unstoppable force now hunting him.',
  },
  oldboy: {
    title: 'Oldboy', year: 2003, runtime: '2h 0m', rating: 'R',
    dir: 'Park Chan-wook',
    poster: { bg: 'linear-gradient(160deg,#2a1a3a,#0f0a1a)', ink: '#C870A8', kicker: 'OLDBOY' },
    imdb: 8.1, letterboxd: 4.4, where: ['MUBI', 'Prime'],
    tags: ['Korean', 'Revenge', 'Unforgettable'],
    blurb: 'A man imprisoned for 15 years with no explanation is suddenly released — and given five days to find out why.',
  },

  // --- VISUALLY STUNNING ---
  mood: {
    title: 'In the Mood for Love', year: 2000, runtime: '1h 38m', rating: 'PG',
    dir: 'Wong Kar-wai',
    poster: { bg: 'linear-gradient(160deg,#7a1f2b,#2b0c12)', ink: '#E7B24C', kicker: '花樣年華' },
    imdb: 8.1, letterboxd: 4.5, where: ['Max', 'Criterion'],
    tags: ['Hong Kong', 'Yearning', 'Impossibly beautiful'],
    blurb: 'Two neighbours in 1960s Hong Kong slowly realise their spouses are having an affair — and find an aching, restrained closeness of their own.',
  },
  budapest: {
    title: 'The Grand Budapest Hotel', year: 2014, runtime: '1h 39m', rating: 'R',
    dir: 'Wes Anderson',
    poster: { bg: 'linear-gradient(160deg,#d98a9e,#b14b6a)', ink: '#3a1322', kicker: 'GRAND BUDAPEST' },
    imdb: 8.1, letterboxd: 4.3, where: ['Disney+', 'Hulu'],
    tags: ['Caper', 'Symmetrical', 'Wickedly funny'],
    blurb: 'A legendary concierge and his lobby boy become entangled in the theft of a priceless painting and the fate of a grand European hotel.',
  },
  mulholland: {
    title: 'Mulholland Drive', year: 2001, runtime: '2h 27m', rating: 'R',
    dir: 'David Lynch',
    poster: { bg: 'linear-gradient(160deg,#1a0533,#0d0d1a)', ink: '#C9973A', kicker: 'MULHOLLAND DR.' },
    imdb: 7.9, letterboxd: 4.4, where: ['Max', 'Criterion'],
    tags: ['Dreamlike', 'Hollywood noir', 'Unforgettable'],
    blurb: 'A bright-eyed actress arrives in Hollywood and befriends a mysterious amnesiac — reality and dream blurring with every scene.',
  },
  handmaiden: {
    title: 'The Handmaiden', year: 2016, runtime: '2h 25m', rating: 'NR',
    dir: 'Park Chan-wook',
    poster: { bg: 'linear-gradient(160deg,#3a1a2a,#1a0a14)', ink: '#E8C8A0', kicker: 'THE HANDMAIDEN' },
    imdb: 8.1, letterboxd: 4.4, where: ['MUBI', 'Prime'],
    tags: ['Korean', 'Lush', 'Twisty'],
    blurb: 'A young woman is hired as a handmaiden to a Japanese heiress living on a secluded estate — but nothing about the situation is what it seems.',
  },

  // --- COMEDY ---
  thelobster: {
    title: 'The Lobster', year: 2015, runtime: '1h 59m', rating: 'R',
    dir: 'Yorgos Lanthimos',
    poster: { bg: 'linear-gradient(160deg,#1a3a3a,#0a1f1f)', ink: '#A8D8D8', kicker: 'THE LOBSTER' },
    imdb: 7.1, letterboxd: 3.8, where: ['Hulu', 'Prime'],
    tags: ['Dark comedy', 'Absurdist', 'Unique'],
    blurb: 'In a dystopian near-future, single people must find a romantic partner within 45 days or be turned into an animal of their choice.',
  },
  insideout: {
    title: 'Inside Out', year: 2015, runtime: '1h 35m', rating: 'PG',
    dir: 'Pete Docter',
    poster: { bg: 'linear-gradient(160deg,#4a1a6b,#1f0a2e)', ink: '#FFD700', kicker: 'INSIDE OUT' },
    imdb: 8.1, letterboxd: 4.2, where: ['Disney+'],
    tags: ['Pixar', 'Emotional', 'Clever'],
    blurb: 'The emotions inside the mind of a young girl must work together as she navigates a major life change — a film that hits differently the older you get.',
  },
  fourweddings: {
    title: 'Four Weddings and a Funeral', year: 1994, runtime: '1h 57m', rating: 'R',
    dir: 'Mike Newell',
    poster: { bg: 'linear-gradient(160deg,#2a3a5a,#0f1a2e)', ink: '#E8D0A8', kicker: 'FOUR WEDDINGS' },
    imdb: 7.1, letterboxd: 3.8, where: ['Prime', 'Peacock'],
    tags: ['British', 'Romantic comedy', 'Charming'],
    blurb: 'A commitment-phobic man keeps running into the same American woman at a series of weddings — and slowly realises she might be the one.',
  },

  // --- SCI-FI / MIND-BENDING ---
  eternal: {
    title: 'Eternal Sunshine of the Spotless Mind', year: 2004, runtime: '1h 48m', rating: 'R',
    dir: 'Michel Gondry',
    poster: { bg: 'linear-gradient(160deg,#1a2a4a,#0a0f2e)', ink: '#A8C8FF', kicker: 'ETERNAL SUNSHINE' },
    imdb: 8.3, letterboxd: 4.4, where: ['Max', 'Prime'],
    tags: ['Mind-bending', 'Romance', 'Heartbreaking'],
    blurb: 'A couple have each other erased from their memories after a painful breakup — told backwards through the fading fragments of their relationship.',
  },
  her: {
    title: 'Her', year: 2013, runtime: '2h 6m', rating: 'R',
    dir: 'Spike Jonze',
    poster: { bg: 'linear-gradient(160deg,#6b2a1a,#2e0f0a)', ink: '#FFB8A0', kicker: 'HER' },
    imdb: 8.0, letterboxd: 4.2, where: ['Max', 'Prime'],
    tags: ['Near-future', 'Lonely', 'Beautiful'],
    blurb: 'A lonely writer develops an unlikely relationship with an AI operating system — a tender, melancholy look at connection in a modern world.',
  },
  moonlight: {
    title: 'Moonlight', year: 2016, runtime: '1h 51m', rating: 'R',
    dir: 'Barry Jenkins',
    poster: { bg: 'linear-gradient(160deg,#0a1a3a,#050a1e)', ink: '#70C8E8', kicker: 'MOONLIGHT' },
    imdb: 7.4, letterboxd: 4.3, where: ['Netflix', 'Prime'],
    tags: ['Coming-of-age', 'Identity', 'Poetic'],
    blurb: 'A young Black man grows up in Miami across three chapters of his life, searching for identity and connection.',
  },

  // --- ADVENTURE / ACTION ---
  madmax: {
    title: 'Mad Max: Fury Road', year: 2015, runtime: '2h 0m', rating: 'R',
    dir: 'George Miller',
    poster: { bg: 'linear-gradient(160deg,#6b3a1a,#2e1a0a)', ink: '#FF8C00', kicker: 'FURY ROAD' },
    imdb: 8.1, letterboxd: 4.3, where: ['Max', 'Netflix'],
    tags: ['Action', 'Relentless', 'Stunning'],
    blurb: 'A woman flees a tyrannical warlord across a post-apocalyptic wasteland in a fury of chrome and fire — two hours of pure cinema.',
  },
  spirited: {
    title: 'Spirited Away', year: 2001, runtime: '2h 5m', rating: 'PG',
    dir: 'Hayao Miyazaki',
    poster: { bg: 'linear-gradient(160deg,#1a3a5a,#0a1f30)', ink: '#FFD080', kicker: 'SPIRITED AWAY' },
    imdb: 8.6, letterboxd: 4.5, where: ['Max', 'Netflix'],
    tags: ['Studio Ghibli', 'Magical', 'Timeless'],
    blurb: 'A young girl wanders into a spirit world and must work in a bathhouse for supernatural beings to save her parents.',
  },
  abouttime: {
    title: 'About Time', year: 2013, runtime: '2h 3m', rating: 'R',
    dir: 'Richard Curtis',
    poster: { bg: 'linear-gradient(160deg,#2a3a6a,#0f1a30)', ink: '#E8D0A8', kicker: 'ABOUT TIME' },
    imdb: 7.8, letterboxd: 4.1, where: ['Netflix', 'Prime'],
    tags: ['Time travel', 'British', 'Warm'],
    blurb: 'A young man discovers he can travel back in time and uses the gift to find love — before learning what moments are truly worth reliving.',
  },
  totoro: {
    title: 'My Neighbor Totoro', year: 1988, runtime: '1h 26m', rating: 'G',
    dir: 'Hayao Miyazaki',
    poster: { bg: 'linear-gradient(160deg,#2a5a2a,#0f2a0f)', ink: '#A8E8A8', kicker: 'MY NEIGHBOR TOTORO' },
    imdb: 8.1, letterboxd: 4.4, where: ['Max', 'Netflix'],
    tags: ['Ghibli', 'Gentle', 'Magical'],
    blurb: 'Two young sisters move to the countryside and discover magical forest spirits — a film of pure, quiet wonder.',
  },
  wonder: {
    title: 'Wonder', year: 2017, runtime: '1h 53m', rating: 'PG',
    dir: 'Stephen Chbosky',
    poster: { bg: 'linear-gradient(160deg,#2a4a6a,#0f1f30)', ink: '#FFD0A8', kicker: 'WONDER' },
    imdb: 7.9, letterboxd: 4.0, where: ['Netflix', 'Prime'],
    tags: ['Family', 'Kindness', 'Uplifting'],
    blurb: 'A boy with a facial difference attends school for the first time — a film about kindness that earns every tear it gets.',
  },
  beforesunrise: {
    title: 'Before Sunrise', year: 1995, runtime: '1h 41m', rating: 'R',
    dir: 'Richard Linklater',
    poster: { bg: 'linear-gradient(160deg,#2a2a5a,#0f0f2a)', ink: '#E8D0FF', kicker: 'BEFORE SUNRISE' },
    imdb: 8.1, letterboxd: 4.3, where: ['Max', 'Criterion'],
    tags: ['Romance', 'Conversation', 'One night'],
    blurb: 'Two strangers meet on a train and spend one night wandering Vienna together — knowing they must part at dawn.',
  },
  biglebowski: {
    title: 'The Big Lebowski', year: 1998, runtime: '1h 57m', rating: 'R',
    dir: 'Coen Brothers',
    poster: { bg: 'linear-gradient(160deg,#3a2a1a,#1a0f0a)', ink: '#A8C870', kicker: 'THE BIG LEBOWSKI' },
    imdb: 8.1, letterboxd: 4.2, where: ['Netflix', 'Prime'],
    tags: ['Cult classic', 'Comedy', 'The Dude'],
    blurb: 'A case of mistaken identity pulls a lazy Californian bowler into a kidnapping scheme — the most laid-back noir ever made.',
  },
  portrait: {
    title: 'Portrait of a Lady on Fire', year: 2019, runtime: '2h 2m', rating: 'NR',
    dir: 'Céline Sciamma',
    poster: { bg: 'linear-gradient(160deg,#1a3a5a,#0a1f2e)', ink: '#FFB880', kicker: 'PORTRAIT' },
    imdb: 8.1, letterboxd: 4.5, where: ['Hulu', 'MUBI'],
    tags: ['French', 'Romance', 'Painterly'],
    blurb: 'An artist is commissioned to paint a young noblewoman who refuses to sit — a slow-burn love story of glances and fire.',
  },
  amelie: {
    title: 'Amélie', year: 2001, runtime: '2h 2m', rating: 'R',
    dir: 'Jean-Pierre Jeunet',
    poster: { bg: 'linear-gradient(160deg,#4a3a1a,#1f1a0a)', ink: '#FFD070', kicker: 'AMÉLIE' },
    imdb: 8.3, letterboxd: 4.3, where: ['Max', 'Criterion'],
    tags: ['French', 'Whimsical', 'Joyful'],
    blurb: 'A shy Parisian waitress secretly orchestrates the happiness of everyone around her — one of the most purely joyful films ever made.',
  },
};

export const STREAM_STYLE = {
  'Max': '#0046FF', 'Criterion': '#16243C', 'Disney+': '#0a2a6b',
  'Hulu': '#1ce783', 'Paramount+': '#0064ff', 'Prime': '#00A8E1',
  'Apple TV': '#111', 'Netflix': '#E50914', 'MUBI': '#0a0a0a',
  'Peacock': '#000000', 'Free on YouTube': '#FF0000',
};
